### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dotsdl** [kairen/kubeadm-ansible#11]
Thanks for putting this together @kairen! I'm using this repo as a source of inspiration for my own kubernetes deployments with ansible, but I both 1) want to properly credit you, and 2) be able to legally use some of what you've written in my own deployments.

In order for others to freely use what you've done (with attribution), do you plan to add a permissive license (perhaps MIT, BSD-3, Apache) to this repository?

**Comment by kairen** [comment]
@dotsdl I've added License as Apache 2.
