### ISSUE TITLE
Not updating apt cache after adding repositories on Ubuntu 16.04

### ISSUE THREAD

**Issue by pauloeliasjr** [kairen/kubeadm-ansible#2]
During playbook execution, the docker-engine package is not installed.

TASK [docker : Add Docker yum repository] *******************************************************************************************************************
skipping: [k8s-master]
skipping: [k8s-node-0]
skipping: [k8s-node-1]

TASK [docker : Install docker engine (RHEL/CentOS)] *********************************************************************************************************
skipping: [k8s-master]
skipping: [k8s-node-0]
skipping: [k8s-node-1]

TASK [docker : Install docker engine (Debian/Ubuntu)] *******************************************************************************************************
fatal: [k8s-master]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'docker-engine' is available"}
fatal: [k8s-node-0]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'docker-engine' is available"}
fatal: [k8s-node-1]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'docker-engine' is available"}
        to retry, use: --limit @/home/ubuntu/kubeadm-ansible/site.retry

A manual "apt-get update" or adding a "update_cache: yes" on roles/docker/tasks/pkg.yml "(install docker engine" task) solves the issue.

**Comment by kairen** [comment]
@pauloeliasjr fixed issue at last commit.
