### ISSUE TITLE
when kubeadm upgrade to v1.10.1 ,it will be fatal

### ISSUE THREAD

**Issue by kaizamm** [kairen/kubeadm-ansible#26]
```
export OS_IMAGE=centos7
```

```
[all:vars]

# Kubernetes
#kube_version=v1.9.3
kube_version=v1.10.1
token=b0f7b8.8d1767876297d85c
```

```
TASK [kubernetes/master : Init Kubernetes cluster] *******************************************
```

### fatal 
fatal: [192.16.35.12]: FAILED! => {"changed": true, "cmd": "kubeadm init --service-cidr 10.96.0.0/12 --kubernetes-version v1.10.1 --pod-network-cidr 10.244.0.0/16 --token b0f7b8.8d1767876297d85c  ", "delta": "0:02:10.301000", "end": "2018-04-21 17:10:02.936757", "msg": "non-zero return code", "rc": 1, "start": "2018-04-21 17:07:52.635757", "stderr": "\t[WARNING FileExisting-crictl]: crictl not found in system path\nSuggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl\ncouldn't initialize a Kubernetes cluster", "stderr_lines": ["\t[WARNING FileExisting-crictl]: crictl not found in system path", "Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl", "couldn't initialize a ........1.10.1", "\t\t- k8s.gcr.io/etcd-amd64:3.1.12 (only if no external etcd endpoints are configured)", "", "If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:", "\t- 'systemctl status kubelet'", "\t- 'journalctl -xeu kubelet'"]}
        to retry, use: --limit @/vagrant/site.retry

PLAY RECAP ****************************************************************************************************************************************************************************
192.16.35.12               : ok=11   changed=2    unreachable=0    failed=1

```
journalctl -xeu kubelet'
```
### output
Apr 21 17:24:50 master1 kubelet[27523]: W0421 17:24:50.988435   27523 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection clea
Apr 21 17:24:50 master1 kubelet[27523]: W0421 17:24:50.988492   27523 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 21 17:24:50 master1 kubelet[27523]: I0421 17:24:50.988537   27523 docker_service.go:244] Docker cri networking managed by cni
Apr 21 17:24:51 master1 kubelet[27523]: I0421 17:24:51.005521   27523 docker_service.go:249] Docker Info: &{ID:NC7E:CYY4:TOY6:QJPM:CP6S:KQT7:GKCY:NF63:MOT6:B2IW:5HQY:FHVS Containers:0
Apr 21 17:24:51 master1 kubelet[27523]: F0421 17:24:51.005645   27523 server.go:233] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd
Apr 21 17:24:51 master1 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Apr 21 17:24:51 master1 systemd[1]: Unit kubelet.service entered failed state.
Apr 21 17:24:51 master1 systemd[1]: kubelet.service failed.
lines 1219-1270/1270 (END)

**Comment by cdrage** [comment]
Honestly, the only work-around is to do a reset and then re-deploy! Closing this as this is a non-issue
