### ISSUE TITLE
Kubeadm

### ISSUE THREAD

**Issue by zakiournani** [kairen/kubeadm-ansible#33]
FAILED! => {"changed": true, "cmd": "kubeadm reset", "delta": "0:00:00.031730", "end": "2018-06-28 11:39:08.070430", "msg": "non-zero return code", "rc": 1, "start": "2018-06-28 11:39:08.038700", "stderr": "Aborted reset operation", "stderr_lines": ["Aborted reset operation"], "stdout": "[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.\n[reset] are you sure you want to proceed? [y/N]: ", "stdout_lines": ["[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.", "[reset] are you sure you want to proceed? [y/N]: "]}

**Comment by cdrage** [comment]
This has been fixed
