### ISSUE TITLE
Reset Kubernetes component failed

### ISSUE THREAD

**Issue by akashtalole** [kairen/kubeadm-ansible#34]
TASK [kubernetes/master : Reset Kubernetes component] ********************************************************************************************************************
Wednesday 04 July 2018  12:49:13 +0530 (0:00:00.486)       0:00:27.593 ******** 
fatal: [10.10.121.244]: FAILED! => {"changed": true, "cmd": "kubeadm reset", "delta": "0:00:00.043798", "end": "2018-07-04 12:51:06.493269", "msg": "non-zero return code", "rc": 1, "start": "2018-07-04 12:51:06.449471", "stderr": "Aborted reset operation", "stderr_lines": ["Aborted reset operation"], "stdout": "[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.\n[reset] are you sure you want to proceed? [y/N]: ", "stdout_lines": ["[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.", "[reset] are you sure you want to proceed? [y/N]: "]}
	to retry, use: --limit @/root/kubeadm-ansible/site.retry

**Comment by yangwenmai** [comment]
As the same to you.

**Comment by kairen** [comment]
The issue has been fixed.
