### ISSUE TITLE
kubeadm is failing to configure master

### ISSUE THREAD

**Issue by zanakabhijit** [kairen/kubeadm-ansible#35]
I tried to run the script on baremetal i.e. ubuntu 16.0.4, gettign following error

`fatal: [10.21.236.81]: FAILED! => {"changed": true, "cmd": "kubeadm reset", "delta": "0:00:00.064778", "end": "2018-07-12 03:29:03.101311", "msg": "non-zero return code", "rc": 1, "start": "2018-07-12 03:29:03.036533", "stderr": "Aborted reset operation", "stderr_lines": ["Aborted reset operation"], "stdout": "[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.\n[reset] are you sure you want to proceed? [y/N]: ", "stdout_lines": ["[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.", "[reset] are you sure you want to proceed? [y/N]: "]}`

**Comment by kairen** [comment]
This issue has been fixed.
