### ISSUE TITLE
Playbook stuck at Join to Kubernetes cluster

### ISSUE THREAD

**Issue by ezio-auditore** [kairen/kubeadm-ansible#57]
The process is stuck at joining kubernetes cluster for past 1hr 30 mins.
Logs: https://pastebin.com/m37fYbtD

**Comment by cdrage** [comment]
@ezio-auditore Could you do it again but with verbose? `-v` on the command line? So we can see what's happening.

**Comment by JsanchezPilo** [comment]
it doesn´t show anything even running with -v

**Comment by JsanchezPilo** [comment]
i just resolved the issue it was my firewall blocking the port 6443
