### ISSUE TITLE
init kubernetes cluster task fails

### ISSUE THREAD

**Issue by adespain** [kairen/kubeadm-ansible#6]
I ran the pre-install.sh manually and it failed at the init task and produced this error:

fatal: [192.16.35.12]: FAILED! => {"changed": true, "cmd": "kubeadm init --service-cidr 10.96.0.0/12 --kubernetes-version v1.8.3 --pod-network-cidr 10.244.0.0/16 --apiserver-advertise-address 192.16.35.12 --token b0f7b8.8d1767876297d85c ", "delta": "0:00:00.284910", "end": "2017-12-21 18:53:55.383813", "msg": "non-zero return code", "rc": 2, "start": "2017-12-21 18:53:55.098903", "stderr": "\t[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.05.0-ce. Max validated version: 17.03\n\t[WARNING FileExisting-crictl]: crictl not found in system path\n[preflight] Some fatal errors occurred:\n\t[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: \"1.9.0\" Control plane version: \"1.8.3\"\n\t[ERROR Swap]: running with swap on is not supported. Please disable swap\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["\t[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.05.0-ce. Max validated version: 17.03", "\t[WARNING FileExisting-crictl]: crictl not found in system path", "[preflight] Some fatal errors occurred:", "\t[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: \"1.9.0\" Control plane version: \"1.8.3\"", "\t[ERROR Swap]: running with swap on is not supported. Please disable swap", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "[init] Using Kubernetes version: v1.8.3\n[init] Using Authorization modes: [Node RBAC]\n[preflight] Running pre-flight checks.", "stdout_lines": ["[init] Using Kubernetes version: v1.8.3", "[init] Using Authorization modes: [Node RBAC]", "[preflight] Running pre-flight checks."]}

**Comment by kairen** [comment]
@adespain Hi, thank you for your reply, I'll update roles in the weekend because Kubernetes v1.9 GA released.

**Comment by kairen** [comment]
Fixed https://github.com/kairen/kubeadm-ansible/commit/5927f7d336f549fba9339f51f72068055fec6695.
