### ISSUE TITLE
Error with the "kubelet version is higher than the control plane version"

### ISSUE THREAD

**Issue by normansu-tw** [kairen/kubeadm-ansible#61]
I got this fatal error .

[preflight] Some fatal errors occurred:\n\t[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: \"1.14.1\" Control plane version: \"1.13.0\"\n[preflight]

Where could I change the control plane version or Kuberlet version ?

Thanks,

Norman Su

**Comment by normansu-tw** [comment]
I open the "group_wars/all.yml",  and change the kube_version as  v1.14.1

Then everything is fine.

**Comment by kilerkarol** [comment]
https://github.com/kairen/kubeadm-ansible/pull/64
